name: commit
run-name: ${{ github.actor }} is commiting 🚀
on: 
  push:

jobs:
  commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.16.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup-node
        uses: actions/setup-node@v3

      - name: Install dependencies  
        run: npm ci

      - name: Unit tests    
        run: npm test

      - name: TS tests      
        run: npm run ts

      - name: Lint tests   
        run: npm run lint